### ISSUE TITLE
Create simple Hello World discord api app.

### ISSUE THREAD

**Issue by mateusz2173** [WebSoftDevs/MusicBot2#3]
- [x] Read [Discord API Docs](https://discordpy.readthedocs.io/en/stable/)
- [x] Create `requirements.txt` file and add discord api to it.
- [x] Create `.env` file containing `BOT_TOKEN` and `PREFIX`
    - You can follow this [tutorial](https://discordjs.guide/preparations/setting-up-a-bot-application.html#creating-your-bot) on how to setup discord app and get token.
    - Set `PREFIX` to `$`
- [x] Create simple hello world app, which will load `BOT_TOKEN` from `.env` file and use DiscordAPI to auth (login) using token. If succeeded print `Hello World` otherwise print `Login failed`.
- [ ] Add simple `README.md` file which will contain description of how to setup app.

**Comment by xNykram** [comment]
@Lorecrafter1590 

Please take care of the last task from the list.
