### ISSUE TITLE
Add message content privilage to bot (test application)

### ISSUE THREAD

**Issue by mateusz2173** [WebSoftDevs/MusicBot2#41]
We need this intent for our commands to work

**Comment by mateusz2173** [comment]
Assigning @xNykram  as I believe you have permissions to change bot intents in discord dev portal.

**Comment by xNykram** [comment]
Can you tell me the name of the access which I need to add?

![image](https://user-images.githubusercontent.com/55030025/202785283-edffc63b-298d-4cb6-ba02-7e95896e4f02.png)

**Comment by mateusz2173** [comment]
We need message content intent, seen on the screen

<img width="1032" alt="Screenshot 2022-11-20 at 23 23 07" src="https://user-images.githubusercontent.com/26009992/202929591-dc8668e6-7613-478c-964e-8ae382c67d5e.png">

**Comment by xNykram** [comment]
Done, should I turn it on also on PROD?

**Comment by mateusz2173** [comment]
Yes, without that bot cannot read channel messages and commands won't work

**Comment by xNykram** [comment]
Done as well on PROD, test it and let me know.
